### ISSUE TITLE
Wallet sync issues.

### ISSUE THREAD

**Issue by p3yot3** [Richcoin-Project/RichCoin#2]
Hello ahmed,

Sorry to post this here, but there is no contact address on the richcoin website.

YoBit seem incapable of synconising their wallet - are there any plans to use a "real" exchange that will actually respond to support tickets?

Regards.

**Comment by ahmedbodi** [comment]
Sorry man, I've no idea. I just did the dev for the coin. Its not actually mine

**Comment by p3yot3** [comment]
Oh? The website is registered in your name......

Not to worry. I was hoping to contact the dev regarding the block explorer being stuck - but that now appears to be offline also.

**Comment by ahmedbodi** [comment]
Yeah im running everything on behalf of someone else, I'll get it all sorted soon

**Comment by p3yot3** [comment]
The block explorer is back up, but it's still stuck at 162371 - current block is 234578

**Comment by p3yot3** [comment]
Block explorer is still not working. Do you have any contact details for the owner so we can get it running again?

**Comment by ahmedbodi** [comment]
I dont im afraid. Ive stopped contact with the owner after he messed me around for payment for my work. Which is why i havent got round to fixing the explorer myself

**Comment by p3yot3** [comment]
Damn. I have some (more) missing yobit deposits, but it's difficult to show them without the explorer working......
I know you're busy, but if you do get time, I'd really appreciate it if you could have a quick look at it.

I hate yobit......lol

**Comment by ahmedbodi** [comment]
All Fixed

**Comment by p3yot3** [comment]
You're the man Ahmed - many thanks!
